# Generated by Django 5.0.6 on 2024-09-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('title', models.TextField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(max_length=256, upload_to='thesis_pdf')),
            ],
        ),
    ]
