# Generated by Django 5.0.6 on 2024-10-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_thesis_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='abstract_pdf',
            field=models.FileField(blank=True, upload_to='abstract_pdf'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='water_pdf',
            field=models.FileField(blank=True, upload_to='water_pdf'),
        ),
    ]
