# Generated by Django 5.0.6 on 2024-11-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_thesis_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.CharField(max_length=100, unique=True)),
                ('pdf_file', models.FileField(upload_to='temporary_pdfs/')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='thesis',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thesis',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
