# Generated by Django 5.0.6 on 2024-11-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_tempurl_thesis_downloads_thesis_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempurl',
            name='title',
            field=models.TextField(default='', max_length=255),
        ),
    ]
